### ISSUE TITLE
Meme appropriation

### ISSUE THREAD

**Issue by harsh13virdi** [jppaled/sarcasm#1]
This isn't sarcasm, its Mocking spongbob meme.

Also the link for this script on your website links to the pollen map. you might wanna check that

**Comment by jppaled** [comment]
I have often seen this same spongebob with the sarcastic writing.

Do you have a meme to suggest ? I don't mind changing it.

As for the link on the site, it is planned to fix it

**Comment by harsh13virdi** [comment]
I mean thats how its documented on [Know your Meme](https://knowyourmeme.com/memes/mocking-spongebob), but then again its your script you can name it whatever. i was just concerned about the broken links on your site :D

**Comment by jppaled** [comment]
Ah ok ! I understand what you meant!

Actually that's not the right term as you say ^^

Btw links are fixed, thanks for your interest
